### Recommendations with MovieTweetings: Most Popular Recommendation

Now that you have created the necessary columns we will be using throughout the rest of the lesson on creating recommendations, let's get started with the first of our recommendations.

To get started, read in the libraries and the two datasets you will be using throughout the lesson using the code below.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tests as t

%matplotlib inline

# Read in the datasets
movies = pd.read_csv('movies_clean.csv')
reviews = pd.read_csv('reviews_clean.csv')
del movies['Unnamed: 0']
del reviews['Unnamed: 0']

#### 1. How To Find The Most Popular Movies

For this notebook, we have a single task.  The task is that no matter the user, we need to provide a list of the recommendations based on simply the most popular items.

For this task, we will consider what is "most popular" based on the following criteria:

* A movie with the highest average rating is considered best
* With ties, movies that have more ratings are better
* A movie must have a minimum of 5 ratings to be considered among the best movies
* If movies are tied in their average rating and number of ratings, the ranking is determined by the movie that is the most recent rating

With these criteria, the goal for this notebook is to take a **user_id** and provide back the **n_top** recommendations.  Use the function below as the scaffolding that will be used for all the future recommendations as well.

In [2]:
reviews.sample(5)

        user_id  movie_id  rating   timestamp                 date
334274    26321   3498820       8  1462907596  2016-05-10 21:13:16
808037    63651    120737       9  1504874516  2017-09-08 14:41:56
613340    47977   1211956       7  1383164328  2013-10-30 22:18:48
448302    35284    816692       9  1585302430  2020-03-27 11:47:10
454333    35734    993846      10  1499680130  2017-07-10 11:48:50

In [3]:
# Function to get average rating
def get_reviews_avg_nr(ival):
    temp_rev = reviews[reviews['movie_id'] == ival]
    i_nr_of_ratings = len(temp_rev)

    if i_nr_of_ratings > 0:
        i_avg_rating = np.average(temp_rev['rating'])
        i_last_rating = temp_rev['date'].max()
    else: 
        i_avg_rating = np.nan
        i_last_rating = np.nan
    
    return i_avg_rating, i_nr_of_ratings, i_last_rating

In [4]:
def get_top_movie_ratings():
    movies['average_rating'] = np.nan
    movies['nr_of_reviews'] = np.nan
    movies['last_review'] = np.nan

    for i in range(len(movies)):
        iavg_rating, i_nr_of_ratings, ilast_rating = get_reviews_avg_nr(movies['movie_id'][i])
        movies.iloc[i, movies.columns.get_loc('average_rating')] = iavg_rating
        movies.iloc[i, movies.columns.get_loc('nr_of_reviews')] = i_nr_of_ratings
        movies.iloc[i, movies.columns.get_loc('last_review')] = ilast_rating    

    movies_rankings = movies[movies['nr_of_reviews'] >= 4]
    
    return(movies_rankings)

global_movies_rankings = get_top_movie_ratings()

In [5]:
def popular_recommendations(user_id, n_top, movies_rankings):
    '''
    INPUT:
    user_id - the user_id of the individual you are making recommendations for
    n_top - an integer of the number recommendations you want back
    OUTPUT:
    top_movies - a list of the n_top recommended movies by movie title in order best to worst
    '''
    movies_rankings = movies_rankings.sort_values(by=['average_rating', 'nr_of_reviews', 'last_review'], ascending=False)
    top_movies = movies_rankings[0:n_top]
    
    return top_movies # a list of the n_top movies as recommended

Usint the three criteria above, you should be able to put together the above function.  If you feel confident in your solution, check the results of your function against our solution. On the next page, you can see a walkthrough and you can of course get the solution by looking at the solution notebook available in this workspace.

In [6]:
# Put your solutions for each of the cases here

# Top 20 movies recommended for id 1
recs_20_for_1 = popular_recommendations(1, 20, global_movies_rankings)

# # Top 5 movies recommended for id 53968
recs_5_for_53968 = popular_recommendations(53968, 5, global_movies_rankings)

# # Top 100 movies recommended for id 70000
recs_100_for_70000 = popular_recommendations(70000, 100, global_movies_rankings)

# Top 35 movies recommended for id 43
recs_35_for_43 = popular_recommendations(43, 35, global_movies_rankings)

In [7]:
### You Should Not Need To Modify Anything In This Cell
ranked_movies = t.create_ranked_df(movies, reviews) # only run this once - it is not fast

# check 1 
assert t.popular_recommendations('1', 20, ranked_movies) == recs_20_for_1,  "The first check failed..."
# check 2
assert t.popular_recommendations('53968', 5, ranked_movies) == recs_5_for_53968,  "The second check failed..."
# check 3
assert t.popular_recommendations('70000', 100, ranked_movies) == recs_100_for_70000,  "The third check failed..."
# check 4
assert t.popular_recommendations('43', 35, ranked_movies) == recs_35_for_43,  "The fourth check failed..."

print("If you got here, looks like you are good to go!  Nice job!")

AttributeError: module 'tests' has no attribute 'create_ranked_df'

**Notice:** This wasn't the only way we could have determined the "top rated" movies.  You can imagine that in keeping track of trending news or trending social events, you would likely want to create a time window from the current time, and then pull the articles in the most recent time frame.  There are always going to be some subjective decisions to be made.  

If you find that no one is paying any attention to your most popular recommendations, then it might be time to find a new way to recommend, which is what the next parts of the lesson should prepare us to do!

### Part II: Adding Filters

Now that you have created a function to give back the **n_top** movies, let's make it a bit more robust.  Add arguments that will act as filters for the movie **year** and **genre**.  

Use the cells below to adjust your existing function to allow for **year** and **genre** arguments as **lists** of **strings**.  Then your ending results are filtered to only movies within the lists of provided years and genres (as `or` conditions).  If no list is provided, there should be no filter applied.

You can adjust other necessary inputs as necessary to retrieve the final results you are looking for!

Try writing a few tests against the test function in our test function.  Below returns the top 20 movies for user 1 based on the specified year and genre filters.  Does yours return the same? 

```
t.popular_recs_filtered('1', 20, ranked_movies, years=['2015', '2016', '2017', '2018'], genres=['History'])
```

In [20]:
movie_rankings = global_movies_rankings

years = ['2015', '2016', '2017', '2018']

if len(years) > 0:
    movie_rankings = movie_rankings[movie_rankings['date'].isin(years)]    
    
movie_rankings.head()

,movie_id,movie,genre,date,1800,1900,2000,News,Film-Noir,Short,...,Animation,Game-Show,Sci-Fi,Family,Crime,Horror,Romance,average_rating,nr_of_reviews,last_review
4027,69049,The Other Side of the Wind (2018),Drama,2018,0,0,1,0,0,0,...,0,0,0,0,0,0,0,6.666667,6.0,2019-07-27 04:16:27
12372,315642,Wazir (2016),Action|Crime|Drama|Mystery|Thriller,2016,0,0,1,0,0,0,...,0,0,0,0,1,0,0,7.757576,33.0,2019-10-10 06:17:31
12933,360556,Fahrenheit 451 (2018),Drama|Sci-Fi|Thriller,2018,0,0,1,0,0,0,...,0,0,1,0,0,0,0,5.148148,27.0,2020-03-27 15:20:22
13015,365545,Nappily Ever After (2018),Comedy|Drama|Romance,2018,0,0,1,0,0,0,...,0,0,0,0,0,0,1,6.918919,37.0,2020-04-22 02:17:49
13124,369610,Jurassic World (2015),Action|Adventure|Sci-Fi,2015,0,0,1,0,0,0,...,0,0,1,0,0,0,0,7.312642,1321.0,2020-01-01 18:35:36

In [32]:
genres = ['Animation', 'Short']

if len(genres) > 0:
    movies_rankings_genres = []
for i in range(len(genres)):
    ifiltered = movie_rankings[movie_rankings[genres[i]] == 1]
    if len(movies_rankings_genres) == 0:
        movies_rankings_genres = ifiltered
    else:    
        movies_rankings_genres = pd.concat([movies_rankings_genres, ifiltered])

,movie_id,movie,genre,date,1800,1900,2000,News,Film-Noir,Short,...,Animation,Game-Show,Sci-Fi,Family,Crime,Horror,Romance,average_rating,nr_of_reviews,last_review
28656,4007502,Frozen Fever (2015),Animation|Short|Adventure|Comedy|Family|Fantas...,2015,0,0,1,0,0,1,...,1,0,0,1,0,0,0,7.272727,22.0,2017-04-10 03:08:04
29003,4171032,World of Tomorrow (2015),Animation|Short|Comedy|Drama|Sci-Fi,2015,0,0,1,0,0,1,...,1,0,1,0,0,0,0,8.500000,6.0,2016-09-06 07:38:29
29913,4661600,Sanjay's Super Team (2015),Animation|Short|Action|Family|Fantasy|Thriller,2015,0,0,1,0,0,1,...,1,0,0,1,0,0,0,7.545455,11.0,2016-12-14 21:58:21
30285,4874696,Borrowed Time (2015),Animation|Short|Drama|Western,2015,0,0,1,0,0,1,...,1,0,0,0,0,0,0,8.200000,5.0,2017-02-22 04:27:55
31279,5452780,Olaf's Frozen Adventure (2017),Animation|Short|Adventure|Comedy|Family|Fantas...,2017,0,0,1,0,0,1,...,1,0,0,1,0,0,0,5.000000,9.0,2018-08-01 17:17:23
31562,5613056,Piper (2016),Animation|Short|Family,2016,0,0,1,0,0,1,...,1,0,0,1,0,0,0,8.516129,31.0,2019-12-25 16:49:29
31889,5807512,Inner Workings (2016),Animation|Short|Adventure|Comedy|Family|Fantasy,2016,0,0,1,0,0,1,...,1,0,0,1,0,0,0,9.000000,8.0,2017-04-19 00:31:27
32632,6267732,LOU (2017),Animation|Short|Comedy|Family|Fantasy,2017,0,0,1,0,0,1,...,1,0,0,1,0,0,0,7.200000,5.0,2019-09-03 09:49:19
34304,8075496,Bao (2018),Animation|Short|Family|Fantasy,2018,0,0,1,0,0,1,...,1,0,0,1,0,0,0,7.904762,21.0,2019-12-25 16:48:37
27286,3472226,Kung Fury (2015),Short|Action|Comedy|Fantasy|Sci-Fi,2015,0,0,1,0,0,1,...,0,0,1,0,0,0,0,8.314607,89.0,2020-02-19 23:10:52
28656,4007502,Frozen Fever (2015),Animation|Short|Adventure|Comedy|Family|Fantas...,2015,0,0,1,0,0,1,...,1,0,0,1,0,0,0,7.272727,22.0,2017-04-10 03:08:04
29003,4171032,World of Tomorrow (2015),Animation|Short|Comedy|Drama|Sci-Fi,2015,0,0,1,0,0,1,...,1,0,1,0,0,0,0,8.500000,6.0,2016-09-06 07:38:29
29526,4448444,Make Like a Dog (2015),Short|Comedy|Drama,2015,0,0,1,0,0,1,...,0,0,0,0,0,0,0,10.000000,5.0,2017-09-09 15:51:48
29913,4661600,Sanjay's Super Team (2015),Animation|Short|Action|Family|Fantasy|Thriller,2015,0,0,1,0,0,1,...,1,0,0,1,0,0,0,7.545455,11.0,2016-12-14 21:58:21
30174,4817576,Stutterer (2015),Short|Drama,2015,0,0,1,0,0,1,...,0,0,0,0,0,0,0,7.333333,6.0,2017-01-02 20:15:57
30285,4874696,Borrowed Time (2015),Animation|Short|Drama|Western,2015,0,0,1,0,0,1,...,1,0,0,0,0,0,0,8.200000,5.0,2017-02-22 04:27:55
30429,4942488,Evil's Evil Cousin (2016),Short|Horror,2016,0,0,1,0,0,1,...,0,0,0,0,0,1,0,10.000000,4.0,2017-03-21 00:09:51
30816,5144072,A Girl in the River: The Price of Forgiveness ...,Documentary|Short,2015,0,0,1,0,0,1,...,0,0,0,0,0,0,0,8.200000,5.0,2017-02-20 21:24:39
30975,5227516,Ellis (2015),Short|Drama,2015,0,0,1,0,0,1,...,0,0,0,0,0,0,0,7.222222,9.0,2016-06-05 00:46:03
31041,5262972,Avengers: Age of Ultron Parody (2015),Short|Comedy,2015,0,0,1,0,0,1,...,0,0,0,0,0,0,0,10.000000,28.0,2016-01-08 02:44:43
31191,5354588,Tom Clancy's the Division: Agent Origins (2016),Short|Action,2016,0,0,1,0,0,1,...,0,0,0,0,0,0,0,8.250000,4.0,2016-03-20 18:14:47
31279,5452780,Olaf's Frozen Adventure (2017),Animation|Short|Adventure|Comedy|Family|Fantas...,2017,0,0,1,0,0,1,...,1,0,0,1,0,0,0,5.000000,9.0,2018-08-01 17:17:23
31430,5538078,Extremis (2016),Documentary|Short,2016,0,0,1,0,0,1,...,0,0,0,0,0,0,0,7.500000,12.0,2018-04-05 15:45:15
31562,5613056,Piper (2016),Animation|Short|Family,2016,0,0,1,0,0,1,...,1,0,0,1,0,0,0,8.516129,31.0,2019-12-25 16:49:29
31805,5751588,Alan Partridge's Scissored Isle (2016),Short|Comedy,2016,0,0,1,0,0,1,...,0,0,0,0,0,0,0,8.000000,4.0,2018-08-24 23:13:22
31889,5807512,Inner Workings (2016),Animation|Short|Adventure|Comedy|Family|Fantasy,2016,0,0,1,0,0,1,...,1,0,0,1,0,0,0,9.000000,8.0,2017-04-19 00:31:27
32308,6073176,The White Helmets (2016),Documentary|Short|Crime|War,2016,0,0,1,0,0,1,...,0,0,0,0,1,0,0,8.142857,35.0,2019-01-17 05:08:19
32497,6186970,The Silent Child (2017),Short|Drama,2017,0,0,1,0,0,1,...,0,0,0,0,0,0,0,6.500000,4.0,2018-04-03 10:13:20
32632,6267732,LOU (2017),Animation|Short|Comedy|Family|Fantasy,2017,0,0,1,0,0,1,...,1,0,0,1,0,0,0,7.200000,5.0,2019-09-03 09:49:19
32998,6571148,Prologue: Last Supper (2017),Short|Horror|Sci-Fi,2017,0,0,1,0,0,1,...,0,0,1,0,0,1,0,6.600000,5.0,2017-12-20 16:43:05
33043,6620846,Wasati (2016),Short|Adventure|Comedy,2016,0,0,1,0,0,1,...,0,0,0,0,0,0,0,7.750000,32.0,2020-03-23 09:35:22
33070,6662050,Five Minutes (2017),Short|Comedy,2017,0,0,1,0,0,1,...,0,0,0,0,0,0,0,10.000000,22.0,2019-04-21 00:29:19
33096,6683920,The Bliss of Being No One (2016),Short|Drama,2016,0,0,1,0,0,1,...,0,0,0,0,0,0,0,8.000000,7.0,2020-01-23 01:27:00
33221,6811134,Is Sumiyati Going to Hell? (2016),Short|Drama,2016,0,0,1,0,0,1,...,0,0,0,0,0,0,0,7.523810,21.0,2020-03-23 09:35:00
33222,6811280,Predicament in Sight (2017),Short|Sci-Fi,2017,0,0,1,0,0,1,...,0,0,1,0,0,0,0,6.000000,11.0,2020-03-24 02:50:29
33361,6939026,Period. End of Sentence. (2018),Documentary|Short,2018,0,0,1,0,0,1,...,0,0,0,0,0,0,0,7.400000,5.0,2019-03-06 21:32:47
33487,7078780,Zygote (2017),Short|Horror|Sci-Fi,2017,0,0,1,0,0,1,...,0,0,1,0,0,1,0,8.500000,4.0,2018-12-09 01:48:56
33731,7332306,Skin (2018),Short|Drama,2018,0,0,1,0,0,1,...,0,0,0,0,0,0,0,8.000000,6.0,2019-08-24 17:52:02
34165,7879350,End Game (2018),Documentary|Short,2018,0,0,1,0,0,1,...,0,0,0,0,0,0,0,7.833333,6.0,2019-02-19 04:55:26
34202,7924820,The Trader (2018),Documentary|Short,2018,0,0,1,0,0,1,...,0,0,0,0,0,0,0,7.250000,4.0,2019-09-06 14:17:07
34304,8075496,Bao (2018),Animation|Short|Family|Fantasy,2018,0,0,1,0,0,1,...,1,0,0,1,0,0,0,7.904762,21.0,2019-12-25 16:48:37
34814,8991520,27 Shaban (2018),Short|Comedy|Drama|Romance,2018,0,0,1,0,0,1,...,0,0,0,0,0,0,1,6.285714,7.0,2020-03-24 02:49:57
35452,11644096,What Did Jack Do? (2017),Short|Comedy|Mystery,2017,0,0,1,0,0,1,...,0,0,0,0,0,0,0,5.750000,8.0,2020-02-05 23:54:02
35453,11644170,What Did Jack Do? (2017),Short|Comedy|Crime|Drama|Fantasy|Music|Mystery...,2017,0,0,1,0,0,1,...,0,0,0,0,1,0,0,8.500000,4.0,2020-01-25 00:34:15

In [43]:
def popular_recs_filtered(user_id, n_top, movies_rankings, years, genres):
    '''
    INPUT:
    user_id - the user_id of the individual you are making recommendations for
    n_top - an integer of the number recommendations you want back
    OUTPUT:
    top_movies - a list of the n_top recommended movies by movie title in order best to worst
    '''

    movies_rankings = movies_rankings.sort_values(by=['average_rating', 'nr_of_reviews', 'last_review'], ascending=False)

    # filter years                         
    if len(years) > 0:
        movies_rankings = movies_rankings[movies_rankings['date'].isin(years)]                              

    # filter by genres
    if len(genres) > 0:
        movies_rankings_genres = []
        for i in range(len(genres)):
            ifiltered = movies_rankings[movies_rankings[genres[i]] == 1]
            if len(movies_rankings_genres) == 0:
                movies_rankings_genres = ifiltered
            else:    
                movies_rankings_genres = pd.concat([movies_rankings_genres, ifiltered])
        movies_rankings = movies_rankings_genres
        
    top_movies = movies_rankings[0:n_top]
    
    return top_movies # a list of the n_top movies as recommended

In [46]:
popular_recs_filtered('1', 5, global_movies_rankings, years=['2015', '2016', '2017', '2018'], genres=['Animation'])

,movie_id,movie,genre,date,1800,1900,2000,News,Film-Noir,Short,...,Animation,Game-Show,Sci-Fi,Family,Crime,Horror,Romance,average_rating,nr_of_reviews,last_review
31343,5476944,Kuroshitsuji: Book of the Atlantic (2017),Animation,2017,0,0,1,0,0,0,...,1,0,0,0,0,0,0,9.4,5.0,2018-06-27 04:33:40
31889,5807512,Inner Workings (2016),Animation|Short|Adventure|Comedy|Family|Fantasy,2016,0,0,1,0,0,1,...,1,0,0,1,0,0,0,9.0,8.0,2017-04-19 00:31:27
32601,6241872,"Ruben Brandt, Collector (2018)",Animation|Action|Crime|Drama|Thriller,2018,0,0,1,0,0,0,...,1,0,0,0,1,0,0,9.0,7.0,2020-01-12 19:52:02
32302,6067832,Batman &amp; Bill (2017),Documentary|Animation|Mystery,2017,0,0,1,0,0,0,...,1,0,0,0,0,0,0,9.0,5.0,2018-07-16 04:33:35
28741,4054952,Gekijouban Fate/Stay Night: Heaven's Feel - I....,Animation|Action|Drama|Fantasy,2017,0,0,1,0,0,0,...,1,0,0,0,0,0,0,9.0,4.0,2020-04-17 06:06:04

In [48]:
num_genre_match = global_ranked_movies[genres].sum(axis=1)
ranked_movies = global_ranked_movies.loc[num_genre_match > 0, :]

NameError: name 'global_ranked_movies' is not defined